# Generated by Django 4.2.3 on 2023-07-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systeme_U', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logement',
            name='qrcode',
        ),
    ]
