# Generated by Django 4.2.3 on 2023-07-26 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systeme_U', '0002_remove_logement_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='logement',
            name='type',
            field=models.ForeignKey(db_column='designation', on_delete=django.db.models.deletion.CASCADE, to='systeme_U.etat'),
        ),
    ]
