# Generated by Django 4.2.1 on 2023-07-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme_U', '0003_etat_alter_logement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
        migrations.AlterField(
            model_name='logement',
            name='type',
            field=models.CharField(max_length=75),
        ),
    ]
